[workspace]
members = [
  "autoWebex",
  "histogram-url-gen",
  "instagram",
  "list",
  "myio",
  "prime-factor",
  "sandbox",
  "stats",
  "table_downloader",
  "techTree",
  "todo",
  "toml_format",
]
resolver = "3"
