[package]
name = "table_downloader"
version = "0.1.0"
edition = "2024"

[dependencies]
csv = "1.3.1"
fantoccini = "0.21.5"
regex = "1.11.1"
tokio = { version = "1.44.2", features = ["full"] }
url = "2.5.4"
